######################################################################################################################################################################################################
# Project:       Juniper
# Application:   juniper-deploy
# File Name:     Dockerfile.test
# Author:        Paul Calnon
#
# Date Created:  2026-03-02
# Last Modified: 2026-03-02
#
# License:       MIT License
# Copyright:     Copyright (c) 2024-2026 Paul Calnon
#
# Description:
#    Lightweight image that packages the integration test suite for use
#    as a test-runner compose service. Runs pytest against live services.
#
# Usage:
#    docker compose --profile test up
#
######################################################################################################################################################################################################

FROM python:3.12-slim

WORKDIR /app

COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

COPY tests/ tests/

CMD ["pytest", "tests/", "-v", "--tb=short"]
