{{- if and .Values.canopy.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "juniper.canopy.fullname" . }}
  labels:
    {{- include "juniper.labels" . | nindent 4 }}
    app.kubernetes.io/component: canopy
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "juniper.selectorLabels" (dict "ctx" . "component" "canopy") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
